### PR TITLE
Fix make stat when some files have unicode characters

### PR DESCRIPTION
**Pull request by aryx**
test plan:
cd ocaml-tree-sitter-semgrep/lang/python
make stat
should now work

### Security

- [x] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Comment by mjambon** [comment]
It's strange that you have to specify `, escapechar='\\'` because standard escaping in CSV doesn't involve backslashes. This is how escaping is normally done:
* `"` -> `""`
* `,` -> `","`
* LF -> `"`LF`"`
* `ab` -> `ab` or `"ab"` or `"a"b`
* `"ab"` -> `""ab""` or """ab"""` or `"""a"b""`
* `\` -> `\` or `"\"`

Can you post an example of problematic input and its CSV encoding?

**Comment by aryx** [comment]
I'm not sure what is going on. I just got the error when doing make stat for python and also recently for
Ruby, so I google for the error and stackoverflow told me to do that.

Try 
cd ocaml-tree-sitter-semgrep/lang/python
make stat
without this PR and you'll get errors.

**Comment by mjambon** [comment]
I ran `make stat` on ruby and didn't get errors. Please post the error message you're getting and/or the link to the StackOverflow page you looked up.

**Comment by aryx** [comment]
Sorry, Rust, not Ruby.
I got errors in aggregate-parse-errors for make stat on python and rust.

**Comment by aryx** [comment]
https://stackoverflow.com/questions/32107790/writing-to-csv-getting-error-need-to-escape-for-a-blank-string

**Comment by mjambon** [comment]
The stats job [works](https://app.circleci.com/pipelines/github/returntocorp/ocaml-tree-sitter-semgrep/1192/workflows/bcba3a49-535b-4706-a99e-80e08226498a/jobs/1233) since I [fixed it two days ago](https://github.com/returntocorp/ocaml-tree-sitter-core/pull/21). I'm still not clear on which error you're getting.

**Comment by aryx** [comment]
with Python 3.10.5 on my Arch Linux machine

**Comment by aryx** [comment]
superseded by https://github.com/returntocorp/ocaml-tree-sitter-core/pull/57

**Pull request closed without merging**
