### PR TITLE
Build system tweaks

### PR DESCRIPTION
**Pull request by sidkshatriya**
Some minor fixes/improvements for build issues I encountered.

### CODE REVIEW

**Comment by sidkshatriya** [comment]
@mjambon 
I submitted this small PR in the hope that it might be helpful to others. Sorry I do not wish to sign a Contributor License Agreement (CLA) for this PR.
 
No issues, I understand that companies might have their own policies. Please feel free to close this PR.

**Comment by sidkshatriya** [comment]
Going ahead and closing pull request. I don't wish to submit it for consideration.

**Comment by mjambon** [comment]
@sidkshatriya sorry for the delay on this, I broke my arm 10 days ago and I'm slowly recovering from surgery.

The goal of the CLA is to allow r2c to change licensing conditions starting at some point in the future without having to request permission from all contributors, which could be impractical. If and when this happens, here's what could happen:
* The project including all community contributions up to that point could continue as a fork distributed only under the old license.
* r2c could continue the project as a proprietary fork.
* New code could switch to an open-source license that protects the business of r2c better than the GPL, such as AGPL or a non-free open-source license [like MongoDB and Elasticsearch did](https://en.wikipedia.org/wiki/Contributor_License_Agreement#Examples).

I'd love to hear if this clarifies things for you or if it confirms what you already knew. I'd like to understand better what makes you reluctant to sign a CLA, and how we could improve the situation. Thanks!

**Comment by sidkshatriya** [comment]
@mjambon That sounds horrible! I hope you are better.

As of today, a large number of projects accept contributions without the requirement of a contributor CLA.

At most one might need to agree to the [Developer Certificate of Origin](https://en.wikipedia.org/wiki/Developer_Certificate_of_Origin) or agree to dual license your contribution or affirm something relatively obvious.

While there are are standard licenses (Apache, MIT, GPL etc) the CLAs tend to be highly custom legal texts. I am happy to place my code contributions under the terms and conditions of these standard licenses. A CLA is an additional legal document I need to agree to and that gives me pause.

(a) I am not a lawyer and I don't have the time and energy to understand the deep implications of a typical CLA which are often custom and framed by the project owners. Because if you do read a typical CLA it does get quite involved in terms of the rights, responsibilities, licenses, warranties and other legal language. These are serious legal documents.
(b) Even if someone would argue that their CLA is "standard" (for some definition of "standard"), conceptually, I don't want to be in asymmetrical situation: not only is my contribution under the licence of the repository but there is now a separate legal agreement that I now need to enter in with another entity. 

The act of a code contribution is fundamentally a community process, in my opinion. By that I mean that the relationship between contributors should be that of peers. I am happy to contribute my code under the code license of the repository. All contributors should be bound by the same license. Ideally speaking, no party should enjoy special rights to the code above and beyond the repo license. That, to me, is truly open source project.

Actually I was not even aware that you needed a CLA to contribute to this repo and was surprised when the CLA assistant bot message popped up. A lot of projects that require CLAs tend to state this upfront -- I don't believe this repo mentions the requirement of a CLA. If you state that upfront, would-be contributors will be able to make their own decision before deciding to submit a contribution.

I _would_ consider a CLA if there were special circumstances. However in this case I don't wish to sign one for the reasons stated above. It's just not worth the hassle.

---
**I want to conclude by saying that** every organization has the right to release its source code with the licenses and CLAs it deems fit so I am not making any judgement about your practices. These are my personal preferences.

**Comment by mjambon** [comment]
Thank you for taking the time to provide this detailed feedback. I [added a note to the readme](https://github.com/returntocorp/ocaml-tree-sitter-core/pull/18) so as to avoid some of this frustration in the future. I don't think we'll change much about the contents of the CLA in the near future, though.

> That sounds horrible! I hope you are better.

thanks! Yes, it's not great 😂 but I'm glad for all the modern tech and for the surgeons who were able to put everything back in place.

**Pull request closed without merging**
