### PR TITLE
feat: allow `pattern`s as external rules

### PR DESCRIPTION
**Pull request by brandonspark**
## What:
This PR allows external rules to be specified via just a single pattern, such as in the case of the Haskell grammar here: https://github.com/tree-sitter/tree-sitter-haskell/blob/3bdba07c7a8eec23f87fa59ce9eb2ea4823348b3/grammar.js#L55

## Why:
This is akin to just a string external, and otherwise cause parser generation to fail.

## How:
Added it as an allowed case in the external rules.

## Test plan:
Included a test which specifies a grammar which uses all three kinds of allowed externals.

### Security

- [x] Change has no security implications (otherwise, ping the security team)

### CODE REVIEW

**Comment by mjambon** [comment]
The public ssh key (deploy key) had been removed on the GitHub side. I think it was done at r2c after CircleCI had a security breach earlier this year. I went to the project settings on CircleCI, deleted the old key and added a new one, which CircleCI pushed to GitHub for us. Let's see if it works.

**Comment by mjambon** [comment]
* The ssh problem is fixed.
* It took more than 2 minutes to "install the dependencies" which isn't great. It should probably be fixed by updating the docker image that comes with opam dependencies pre-installed.
* The job failed in the pre-commit stage, complaining about whitespace.

**Review by mjambon — APPROVED** [review]
This is great. Thank you, especially for the test with the `scanner.c`.

**Comment by aryx** [comment]
Nice work! Exciting! We gonna support haskell!!

**Pull request merged**
